# app/notifications/constants.py

LIKE_POST = "LIKE_POST"
COMMENT_POST = "COMMENT_POST"
REPOST_POST = "REPOST_POST"
FOLLOW_USER = "FOLLOW_USER"
REPLY_COMMENT = "REPLY_COMMENT"
LIKE_COMMENT = "LIKE_COMMENT"

ALL_NOTIFICATION_TYPES = {
    LIKE_POST,
    COMMENT_POST,
    REPOST_POST,
    FOLLOW_USER,
    REPLY_COMMENT,
    LIKE_COMMENT
}