"""add last_read_message_id

Revision ID: 02e1606ead7a
Revises: aad98ecc9ae9
Create Date: 2026-06-23 15:28:14.252169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e1606ead7a'
down_revision = 'aad98ecc9ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_message_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_column('last_read_message_id')

    # ### end Alembic commands ###
