"""add follow_request system

Revision ID: 03769b5440ec
Revises: 086adecaf936
Create Date: 2026-05-05 16:16:35.111810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03769b5440ec'
down_revision = '086adecaf936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_requests', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
