"""Refactor message media for MinIO storage

Revision ID: 06d1db796132
Revises: 133b234f455a
Create Date: 2026-07-01 12:41:43.861798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06d1db796132'
down_revision = '133b234f455a'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("message_media", schema=None) as batch_op:

        # add temporarily nullable
        batch_op.add_column(
            sa.Column("object_key", sa.Text(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("filename", sa.String(length=255), nullable=True)
        )

        batch_op.add_column(
            sa.Column("mime_type", sa.String(length=120), nullable=True)
        )

        batch_op.add_column(
            sa.Column("size", sa.BigInteger(), nullable=True)
        )

        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.func.now(),
                nullable=False
            )
        )


    # fill old records
    op.execute("""
        UPDATE message_media
        SET
            object_key = file_url,
            filename = split_part(file_url, '/', array_length(string_to_array(file_url, '/'),1)),
            mime_type = 'application/octet-stream',
            size = 0
        WHERE object_key IS NULL
    """)


    # now enforce NOT NULL
    with op.batch_alter_table("message_media", schema=None) as batch_op:

        batch_op.alter_column(
            "object_key",
            nullable=False
        )

        batch_op.alter_column(
            "filename",
            nullable=False
        )

        batch_op.alter_column(
            "mime_type",
            nullable=False
        )

        batch_op.alter_column(
            "size",
            nullable=False
        )

        batch_op.create_index(
            batch_op.f("ix_message_media_message_id"),
            ["message_id"],
            unique=False
        )

        batch_op.drop_column("uploaded_at")
        batch_op.drop_column("file_url")
        batch_op.drop_column("file_type")


    with op.batch_alter_table("messages", schema=None) as batch_op:

        batch_op.drop_column("media_type")
        batch_op.drop_column("media_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_message_media_message_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('size')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('filename')
        batch_op.drop_column('object_key')

    # ### end Alembic commands ###
