"""add password reset fields

Revision ID: 086adecaf936
Revises: 9bd83fd18b87
Create Date: 2026-05-05 15:47:15.998738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086adecaf936'
down_revision = '9bd83fd18b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
