"""prepare account deletion behavior

Revision ID: 10c263595bdc
Revises: ce0599fba1d5
Create Date: 2026-08-13 16:54:53.044315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c263595bdc'
down_revision = 'ce0599fba1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('comments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('conversation_archives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_archives_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_archives_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation_clears', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_clears_conversation_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_clears_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation_hides', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_hides_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_hides_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('conversation_participants_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_requests_receiver_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_requests_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('muted_conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('muted_conversation_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('muted_conversation_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pinned_messages', schema=None) as batch_op:
        batch_op.alter_column('pinned_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('pinned_messages_pinned_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['pinned_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinned_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pinned_messages_pinned_by_fkey'), 'users', ['pinned_by'], ['id'])
        batch_op.alter_column('pinned_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('muted_conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('muted_conversation_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('muted_conversation_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_requests_sender_id_fkey'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_requests_receiver_id_fkey'), 'users', ['receiver_id'], ['id'])

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_participants_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('conversation_hides', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_hides_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_hides_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('conversation_clears', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_clears_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_clears_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('conversation_archives', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_archives_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_archives_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
