"""Add unique constraint to pinned messages

Revision ID: 133b234f455a
Revises: 02e1606ead7a
Create Date: 2026-06-27 15:33:33.265929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133b234f455a'
down_revision = '02e1606ead7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pinned_messages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_pinned_message', ['message_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinned_messages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pinned_message', type_='unique')

    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
