"""add cover url to profiles

Revision ID: 203cc6389068
Revises: b81f3a39fe83
Create Date: 2026-08-22 20:08:01.625098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203cc6389068'
down_revision = 'b81f3a39fe83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
