"""add muted conversations

Revision ID: 229c9f7c6cc6
Revises: d56144eb2b30
Create Date: 2026-08-06 17:18:12.773613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229c9f7c6cc6'
down_revision = 'd56144eb2b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muted_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_always', sa.Boolean(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_muted_conversation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muted_conversation')
    # ### end Alembic commands ###
