"""add audio metadata to message_media

Revision ID: 2bb426f09f18
Revises: c67b278369cb
Create Date: 2026-07-02 17:35:29.465665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb426f09f18'
down_revision = 'c67b278369cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('album', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cover_object_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.drop_column('cover_object_key')
        batch_op.drop_column('duration')
        batch_op.drop_column('album')
        batch_op.drop_column('artist')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
