"""add email verification system

Revision ID: 306658515800
Revises: 8126ca1ea411
Create Date: 2026-05-21 19:48:10.894730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306658515800'
down_revision = '8126ca1ea411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_token_expiry')

    # ### end Alembic commands ###
