"""add pending google registrations

Revision ID: 321c9695d6af
Revises: 14d967e1aaef
Create Date: 2026-08-13 11:00:33.134741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321c9695d6af'
down_revision = '14d967e1aaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_google_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    with op.batch_alter_table('pending_google_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_google_registrations_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_google_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_google_registrations_email'))

    op.drop_table('pending_google_registrations')
    # ### end Alembic commands ###
