"""add email otp verification

Revision ID: 3b465fc9cdce
Revises: 306658515800
Create Date: 2026-05-21 20:31:33.283471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b465fc9cdce'
down_revision = '306658515800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_expiry')
        batch_op.drop_column('email_verification_code')

    # ### end Alembic commands ###
