"""add link views

Revision ID: 3c0775a40c09
Revises: a509e1af63c1
Create Date: 2026-08-27 14:43:47.198007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0775a40c09'
down_revision = 'a509e1af63c1'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'link_views',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('link_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('opened_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['link_id'],
            ['message_links.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'link_id',
            'user_id',
            name='uq_link_user_view',
        ),
    )

    with op.batch_alter_table(
        'link_views',
        schema=None,
    ) as batch_op:

        batch_op.create_index(
            batch_op.f('ix_link_views_link_id'),
            ['link_id'],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f('ix_link_views_user_id'),
            ['user_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('is_forwarded',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('link_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_link_views_link_id'))

    op.drop_table('link_views')
    # ### end Alembic commands ###
