"""sync message model

Revision ID: 4736adb9b5cb
Revises: a92a6443d541
Create Date: 2026-05-06 13:05:30.771914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4736adb9b5cb'
down_revision = 'a92a6443d541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_requested_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('delete_requested_at')

    # ### end Alembic commands ###
