"""Add video metadata

Revision ID: 4acaab7273aa
Revises: d20dd951997e
Create Date: 2026-07-22 15:43:03.356090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acaab7273aa'
down_revision = 'd20dd951997e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_object_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_object_key')
        batch_op.drop_column('video_height')
        batch_op.drop_column('video_width')

    # ### end Alembic commands ###
