"""add repost system

Revision ID: 545ff0d8c24f
Revises: d1b7940c690b
Create Date: 2026-05-16 10:54:42.214296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545ff0d8c24f'
down_revision = 'd1b7940c690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reposts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reposts_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reposts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reposts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reposts_user_id'))
        batch_op.drop_index(batch_op.f('ix_reposts_post_id'))

    op.drop_table('reposts')
    # ### end Alembic commands ###
