"""add soft delete flag to users

Revision ID: 5a52f7d5ac36
Revises: 10c263595bdc
Create Date: 2026-08-14 13:55:37.547880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a52f7d5ac36'
down_revision = '10c263595bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_receiver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column( sa.Column( "is_deleted", sa.Boolean(), nullable=False, server_default=sa.false(),))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_receiver_id_fkey'), 'users', ['receiver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
