"""add receiver_id to messages

Revision ID: 8126ca1ea411
Revises: ca3eeed5b897
Create Date: 2026-05-21 19:34:48.084655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8126ca1ea411'
down_revision = 'ca3eeed5b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_forwarded_from_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'messages', ['forwarded_from_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_forwarded_from_id_fkey'), 'messages', ['forwarded_from_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
