"""add pending registrations

Revision ID: 841158df99bd
Revises: 229c9f7c6cc6
Create Date: 2026-08-10 20:05:58.874043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841158df99bd'
down_revision = '229c9f7c6cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('verification_code_hash', sa.String(length=255), nullable=False),
    sa.Column('verification_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_registrations_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_registrations_email'))

    op.drop_table('pending_registrations')
    # ### end Alembic commands ###
