"""add backup_content to messages

Revision ID: 8438248f5d4a
Revises: 81e5ec93a8c4
Create Date: 2026-05-07 18:00:34.109290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8438248f5d4a'
down_revision = '81e5ec93a8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_conversation_participant', ['conversation_id', 'user_id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('backup_content')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint('unique_conversation_participant', type_='unique')

    # ### end Alembic commands ###
