"""fix repost + comment relationships

Revision ID: 9a2cbb4c7c07
Revises: 0e71142ae628
Create Date: 2026-05-17 09:22:06.626293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a2cbb4c7c07'
down_revision = '0e71142ae628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comments_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reposts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_reposts_post_id'))
        batch_op.drop_index(batch_op.f('ix_reposts_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reposts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reposts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reposts_post_id'), ['post_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comments_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
