"""fix message relationships

Revision ID: 9d9e6a791278
Revises: deaa007e4710
Create Date: 2026-05-09 20:22:30.655945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9e6a791278'
down_revision = 'deaa007e4710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forwarded_from_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_forwarded', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'messages', ['forwarded_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_forwarded')
        batch_op.drop_column('forwarded_from_id')

    # ### end Alembic commands ###
