"""add message links

Revision ID: a509e1af63c1
Revises: 72184da5a4a3
Create Date: 2026-08-26 10:38:47.291113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a509e1af63c1'
down_revision = '72184da5a4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_links_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_links_normalized_url'), ['normalized_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_links_normalized_url'))
        batch_op.drop_index(batch_op.f('ix_message_links_message_id'))

    op.drop_table('message_links')
    # ### end Alembic commands ###
