"""create calls table

Revision ID: a51bbf792854
Revises: 3c0775a40c09
Create Date: 2026-08-29 09:33:40.494815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51bbf792854'
down_revision = '3c0775a40c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_caller_id'), ['caller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_status'))
        batch_op.drop_index(batch_op.f('ix_calls_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_calls_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_calls_caller_id'))

    op.drop_table('calls')
    # ### end Alembic commands ###
