"""add conversation requets state and args

Revision ID: aad98ecc9ae9
Revises: 664b671e8e90
Create Date: 2026-06-19 11:14:40.940183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad98ecc9ae9'
down_revision = '664b671e8e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint('unique_conversation_request', ['sender_id', 'receiver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_requests', schema=None) as batch_op:
        batch_op.drop_constraint('unique_conversation_request', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
