"""add message editing and delete flags

Revision ID: aeab42fd7f1c
Revises: e3375d31a740
Create Date: 2026-05-06 11:28:42.671629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeab42fd7f1c'
down_revision = 'e3375d31a740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_for_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_for_receiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('deleted_for_receiver')
        batch_op.drop_column('deleted_for_sender')
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
