"""add inbox system

Revision ID: b26efbbdec9c
Revises: 03769b5440ec
Create Date: 2026-05-06 09:53:05.296308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26efbbdec9c'
down_revision = '03769b5440ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_follow'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_follow'), ['follower_id', 'following_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
