"""add delete system to messages

Revision ID: bb09d8aea0b0
Revises: aeab42fd7f1c
Create Date: 2026-05-06 12:20:32.269848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb09d8aea0b0'
down_revision = 'aeab42fd7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_for_everyone', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_for_users', sa.JSON(), nullable=True))
        batch_op.drop_column('deleted_for_receiver')
        batch_op.drop_column('deleted_for_sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_for_sender', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_for_receiver', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('deleted_for_users')
        batch_op.drop_column('deleted_for_everyone')

    # ### end Alembic commands ###
