"""remove dm user columns and use participants

Revision ID: c226722af7f2
Revises: 6a44861b7f1c
Create Date: 2026-05-12 18:09:56.568776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c226722af7f2'
down_revision = '6a44861b7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_user1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conversations_user2'), type_='foreignkey')
        batch_op.drop_column('user1_id')
        batch_op.drop_column('user2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_conversations_user2'), 'users', ['user2_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conversations_user1'), 'users', ['user1_id'], ['id'])

    # ### end Alembic commands ###
