"""create media views

Revision ID: c67b278369cb
Revises: 6d9846c4b0b1
Create Date: 2026-07-02 12:05:25.453090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c67b278369cb'
down_revision = '6d9846c4b0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opened_at',sa.DateTime(),nullable=False,server_default=sa.func.now(),),
    sa.ForeignKeyConstraint(['media_id'], ['message_media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'user_id', name='uq_media_user_view')
    )
    with op.batch_alter_table('media_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_views_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_views_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.drop_column('viewed')
        batch_op.drop_column('viewed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('viewed', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('media_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_media_views_media_id'))

    op.drop_table('media_views')
    # ### end Alembic commands ###
