"""add cascade delete to conversation + comment likes

Revision ID: ca3eeed5b897
Revises: e59c2976e421
Create Date: 2026-05-21 19:03:06.082171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3eeed5b897'
down_revision = 'e59c2976e421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_likes_comment_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_likes_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_participants_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_participants_conversation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_participants_conversation_id_fkey'), 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_participants_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_likes_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_likes_comment_id_fkey'), 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###
