"""Add media_kind and waveform to message_media

Revision ID: d20dd951997e
Revises: 2bb426f09f18
Create Date: 2026-07-03 13:54:07.787407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20dd951997e'
down_revision = '2bb426f09f18'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("message_media", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "media_kind",
                sa.String(length=20),
                nullable=False,
                server_default="file",
            )
        )

        batch_op.add_column(
            sa.Column(
                "waveform",
                sa.JSON(),
                nullable=True,
            )
        )

        batch_op.alter_column(
            "media_kind",
            server_default=None,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_media', schema=None) as batch_op:
        batch_op.drop_column('waveform')
        batch_op.drop_column('media_kind')

    # ### end Alembic commands ###
