"""add delivered_at and read_at to messages

Revision ID: d4b6bc096dbb
Revises: d8563bf8944a
Create Date: 2026-05-06 15:54:07.464524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4b6bc096dbb'
down_revision = 'd8563bf8944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delete_requested_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('sent', 'delivered', 'read', name='message_status'),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('sent', 'delivered', 'read', name='message_status'),
               nullable=False)
        batch_op.drop_column('delete_requested_at')
        batch_op.drop_column('read_at')
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
