"""add message delivery states

Revision ID: d8563bf8944a
Revises: 4736adb9b5cb
Create Date: 2026-05-06 13:55:29.789373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8563bf8944a'
down_revision = '4736adb9b5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('sent', 'delivered', 'read', name='message_status'), nullable=False))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('read_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
