"""add follow system

Revision ID: dc09d670b8df
Revises: b2dc1b598479
Create Date: 2026-05-05 10:17:40.501635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc09d670b8df'
down_revision = 'b2dc1b598479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_user_follow')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follower_id', ['follower_id'], unique=False)
        batch_op.create_index('idx_following_id', ['following_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_following_id')
        batch_op.drop_index('idx_follower_id')

    op.drop_table('follows')
    # ### end Alembic commands ###
