"""add cascade deletes to notifications

Revision ID: e59c2976e421
Revises: e237e0a03642
Create Date: 2026-05-21 18:41:12.154714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59c2976e421'
down_revision = 'e237e0a03642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notifications_post_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notifications_actor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notifications_comment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['actor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_comment_id_fkey'), 'comments', ['comment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('notifications_actor_id_fkey'), 'users', ['actor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('notifications_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
