"""add system message fields

Revision ID: e6fdc64d0127
Revises: 4acaab7273aa
Create Date: 2026-07-23 17:07:03.876071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fdc64d0127'
down_revision = '4acaab7273aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=False, server_default="text", ))
        batch_op.add_column(sa.Column('system_event', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_message_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'messages', ['target_message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('target_message_id')
        batch_op.drop_column('system_event')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
