"""add conversation archives table

Revision ID: ef32063d484b
Revises: e6fdc64d0127
Create Date: 2026-08-04 13:50:34.636687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef32063d484b'
down_revision = 'e6fdc64d0127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', name='uq_user_conversation_archive')
    )
    with op.batch_alter_table('conversation_archives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_archives_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_archives_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_archives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_archives_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_archives_conversation_id'))

    op.drop_table('conversation_archives')
    # ### end Alembic commands ###
