"""Add accepted column to Follow

Revision ID: fd3cee309987
Revises: 56b5c5ff1a46
Create Date: 2026-05-23 12:15:12.700153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3cee309987'
down_revision = '56b5c5ff1a46'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("follows", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("accepted", sa.Boolean(), nullable=False, server_default="false")
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
