"""add message reactions

Revision ID: fe8755ba9f39
Revises: a54067a9c0ec
Create Date: 2026-05-08 15:22:34.250381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8755ba9f39'
down_revision = 'a54067a9c0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_reply_to_message_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_reply_to_message_id_fkey'), 'messages', ['reply_to_message_id'], ['id'])

    # ### end Alembic commands ###
